from typing import Dict

class PythonEngine:
    def __init__(
        self,
        *,
        env: Dict[str, str],
        datamodel: str,
        # TODO: enum
        log_level: str,
        log_queries: bool,
        datasource_overrides: Dict[str, str],
        ignore_env_var_errors: bool,
    ) -> None: ...
    def query_sync(self, query: str) -> str: ...
    def connect_sync(self, timeout: int) -> None: ...
    def disconnect_sync(self) -> None: ...
    async def query(self, query: str) -> str: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...

class PrismaRustError(Exception): ...
class JsonError(PrismaRustError): ...
class CrossbeamError(PrismaRustError): ...
class NotConnectedError(PrismaRustError): ...
class AlreadyConnectedError(PrismaRustError): ...
class ConfigurationError(PrismaRustError): ...
