coverage:
  status:
    project:
      # default is required to exist
      default: false
      tests:
        target: 100%
        paths:
          - "tests/"
        branches:
          - main
      databases:
        target: 100%
        paths:
          - "databases/"
        branches:
          - main
      prisma:
        paths:
          - "!tests/"
          - "!databases/"
        target: auto
        threshold: 10%
        branches:
          - main

    patch: off

ignore:
  - "src/prisma/generator/templates/**/*"
