from typing import Tuple

class Hashids(object):
    def __init__(self, salt: str = ..., min_length: int = ..., alphabet: str = ...) -> None: ...
    def encode(self, *values: int) -> str: ...
    def decode(self, hashid: str) -> Tuple[int, ...]: ...
