import pkgutil
from pathlib import Path
from typing_extensions import Protocol, runtime_checkable


@runtime_checkable
class SourceLoader(Protocol):
    def get_filename(self) -> str:
        ...


def cleanup() -> None:
    """Remove python files that are auto-generated by Prisma Client Python"""

    # pkgutil.get_loader() can return a loader that doesn't have access to
    # the packages source location. We should provide an easy to understand error
    # for this case even if it is incredibly unlikey (if not impossible)
    # to happen in our use case
    loader = pkgutil.get_loader('prisma')
    if not isinstance(loader, SourceLoader):
        raise RuntimeError(f'Received unresolvable import loader: {loader}')

    # as we rely on prisma to cleanup the templates for us
    # we have to make sure that prisma is importable and
    # if any template rendered incorrect syntax or any other
    # kind of error that wasn't automatically cleaned up,
    # prisma will raise an error when imported,
    # removing prisma/client.py fixes this as it is
    # the only default entrypoint to generated code.
    pkg_path = loader.get_filename()
    file = Path(pkg_path).parent / 'client.py'
    if file.exists():
        file.unlink()

    from prisma.generator.generator import BASE_PACKAGE_DIR, cleanup_templates

    cleanup_templates(rootdir=BASE_PACKAGE_DIR)
    print(f'Successfully removed all auto-generated files from {pkg_path}')


if __name__ == '__main__':
    cleanup()
