from pathlib import Path
from prisma.generator import BaseGenerator, Manifest, Data

TEMPLATE = '''
# My Prisma Schema

This file is automatically generated every time `prisma generate` is ran.
'''

MODEL_TEMPLATE = '''
## {0.name} Model
'''


class MyGenerator(BaseGenerator):
    def get_manifest(self) -> Manifest:
        return Manifest(
            name='My Cool Generator',
            default_output='schema.md',
        )

    def generate(self, data: Data) -> None:
        content = TEMPLATE
        for model in data.dmmf.datamodel.models:
            content += MODEL_TEMPLATE.format(model)

        file = Path(data.generator.output.value)
        file.write_text(content)


if __name__ == '__main__':
    MyGenerator.invoke()
