name: Publish to PyPi
on:
  push:
    branches:
      - refactor/publish
  workflow_dispatch:

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -U -r requirements/dev.txt

      - name: Build Package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload to PyPi
        run: |
          twine upload --repository testpypi -u __token__ -p ${{ secrets.TESTPYPI_TOKEN }} dist/*
