from pathlib import Path
from prisma.generator import BaseGenerator, Manifest, DefaultData

TEMPLATE = """
# My Prisma Schema

This file is automatically generated every time `prisma generate` is ran.
"""

MODEL_TEMPLATE = """
## {0.name} Model
"""


class MyGenerator(BaseGenerator):
    def get_manifest(self) -> Manifest:
        return Manifest(
            name='My Cool Generator',
            default_output='schema.md',
        )

    def generate(self, data: DefaultData) -> None:
        content = TEMPLATE
        for model in data.dmmf.datamodel.models:
            content += MODEL_TEMPLATE.format(model)

        # make sure you use the output value given in the Prisma DMMF
        # as the output location can be customised!
        file = Path(data.generator.output.value)
        file.write_text(content)


if __name__ == '__main__':
    MyGenerator.invoke()
